@baseUrl = http://127.0.0.1:8000


# @name home
GET {{baseUrl}}

###

# @name register
post {{baseUrl}}/users
Content-Type: application/json

{
  "username": "testuser3",
  "firstName": "Test3",
  "lastName": "User3",
  "email": "test3@example.com",
  "password": "123456"
}