@baseUrl = http://127.0.0.1:8000
@simpleToken = Token {{login.response.body.token}}

# @name home
GET {{baseUrl}}

### 
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "testt@example.com",
  "password": "Test1234"
}

### 
# @name logout
get {{baseUrl}}/auth/logout
Authorization: {{simpleToken}}

###
# @name listUser
get {{baseUrl}}/users
Authorization: {{simpleToken}}


###
# @name createUser/
post {{baseUrl}}/users
Content-Type: application/json

{
  "username": "test",
  "firstName": "Test",
  "lastName": "User",
  "email": "testt@example.com",
  "password": "Test1234"
}

###
# @name readUser
GET {{baseUrl}}/users/6a43708671281dea0d7de841
Authorization: {{simpleToken}}

###

# @name updateUser
put {{baseUrl}}/users/6a44411785f1ce126978ee53
Content-Type: application/json
Authorization: {{simpleToken}}

{
    "username" : "testuserupda"
}

###
# @name deleteUser
DELETE {{baseUrl}}/users/6a44411785f1ce126978ee53
Authorization: {{simpleToken}}

####### Category #######

###
# @name listCategory
GET {{baseUrl}}/categories
Content-Type: application/json
Authorization: {{simpleToken}}

###
# @name createCategory
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: {{simpleToken}}

{
  "name": "Security"
}

###
# @name readCategory
GET {{baseUrl}}/categories/6a44dc14ea0e99bf08a18ba7
Authorization: {{simpleToken}}

###
# @name updateCategory
put {{baseUrl}}/categories/6a44dc14ea0e99bf08a18ba7
Content-Type: application/json
Authorization: {{simpleToken}}

{
    "name" : "World"
}

###
# @name deleteCategory
DELETE {{baseUrl}}/categories/6a44dc14ea0e99bf08a18ba7
Authorization: {{simpleToken}}

####### Blog #######

###
# @name listBlog
GET {{baseUrl}}/blogs
Content-Type: application/json
Authorization: {{simpleToken}}

###
# @name createBlog
POST {{baseUrl}}/blogs
Content-Type: application/json
Authorization: {{simpleToken}}

{
  "categoryId": "6a44de6130ca4093a3fc3bac",
  "title": "Blog Title 2",
  "content": "Blog Content 2",
  "image": "http://imageURL",
  "isPublish": true
}

###
# @name listBlog
GET {{baseUrl}}/blogs
Content-Type: application/json
Authorization: {{simpleToken}}

###
# @name readBlog
GET {{baseUrl}}/blogs/6a462077680ebfea9d65755f
Authorization: {{simpleToken}}

###
# @name updateBlog
put {{baseUrl}}/blogs/6a4616cc4501b1eb455dfe89
Content-Type: application/json
Authorization: {{simpleToken}}

{
  "categoryId": "6a44de6130ca4093a3fc3bac",
  "title": "Blog Title 1 updated",
  "content": "Blog Content 1",
  "image": "http://imageURL",
  "isPublish": true
}

###
# @name toggleLikeBlog
POST {{baseUrl}}/blogs/6a462077680ebfea9d65755f/postlike
Authorization: {{simpleToken}}



####### Comment #######
###
# @name listComments
GET {{baseUrl}}/comments
Authorization: {{simpleToken}}

###
# @name createComment
POST {{baseUrl}}/comments
Content-Type: application/json
Authorization: {{simpleToken}}

{
  "blogId": "6a4616cc4501b1eb455dfe89",
  "comment": "Bu benim yorumum."
}

###
# @name readComment
GET {{baseUrl}}/comments/6a465ca4410956609ad7b72a
Authorization: {{simpleToken}}

###
# @name updateComment
PUT {{baseUrl}}/comments/6a465ca4410956609ad7b72a
Content-Type: application/json
Authorization: {{simpleToken}}

{
  "comment": "Güncellenmiş yorum."
}

###
# @name deleteComment
DELETE {{baseUrl}}/comments/6a465ca4410956609ad7b72a
Authorization: {{simpleToken}}

