@baseUrl = http://127.0.0.1:8000
@simpleToken = Token {{login.response.body.token}}

# @name home
GET {{baseUrl}}


### 
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "test@example.com",
  "password": "Test1234"
}

###
# @name listUser
get {{baseUrl}}/users
Authorization: {{simpleToken}}


###
# @name createUser/
post {{baseUrl}}/users
Content-Type: application/json

{
  "username": "testuser",
  "firstName": "Test",
  "lastName": "User",
  "email": "test@example.com",
  "password": "Test1234"
}

###
# @name readUser
GET {{baseUrl}}/users/6a43708671281dea0d7de841
Authorization: {{simpleToken}}

###

# @name updateUser
put {{baseUrl}}/users/6a44411785f1ce126978ee53
Content-Type: application/json
Authorization: {{simpleToken}}

{
    "username" : "testuserupda"
}

###
# @name deleteUser
DELETE {{baseUrl}}/users/6a44411785f1ce126978ee53
Authorization: {{simpleToken}}

### 
# @name logout
get {{baseUrl}}/auth/logout
Authorization: {{simpleToken}}